//独立COOKIE文件     ck在``里面填写，多账号换行

let qmydtokenVal = `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDkwNTgxMywiZXhwIjoyMDUzNjUwNTgxMywibmJmIjoxNjE0OTA1ODEzLCJqdGkiOiJudENiSW9obms4bTd1UTFLIiwic3ViIjoxMTU5MzIsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.gdljw3xNaVlyLIZM-BQms8IK6aySfnxuj9F-einPIUg
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNTA0Mjk1NSwiZXhwIjoyMDUzNjY0Mjk1NSwibmJmIjoxNjE1MDQyOTU1LCJqdGkiOiJGVEhjbkpDVzhrZDQyVVR4Iiwic3ViIjoxMTU5OTUsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.uURgEWe2p_jICRuv7P8GysRoAiXFpYcYRwT11HUzelQ
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNTA0NDM4NCwiZXhwIjoyMDUzNjY0NDM4NCwibmJmIjoxNjE1MDQ0Mzg0LCJqdGkiOiIxT3pqcUEzaHpicjNVWFV3Iiwic3ViIjoxMTYzMTMsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.ilBXm_Dxm_asupVsV_75moaGEn5BjlXbIHb2k_lGY6Q
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgxNzExMiwiZXhwIjoyMDUzNjQxNzExMiwibmJmIjoxNjE0ODE3MTEyLCJqdGkiOiJWTUREWTBQTEJ4NHVMYWNwIiwic3ViIjoxMTU5ODYsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.9I90x6Z4-FAy-7NLYk7IDLMIMJJw8kqEWF7c--_icHU`








let qmydcookie = {

    qmydtokenVal: qmydtokenVal,

}

module.exports = qmydcookie
